force-app/main/default/objects/Opportunity/fields/Democracy__c.field-meta.xml
<CustomField>
    <fullName>Democracy__c</fullName>
    <label>Democracy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Disaster__c.field-meta.xml
<CustomField>
    <fullName>Disaster__c</fullName>
    <label>Disaster</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <label>Labor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Thematic__c.field-meta.xml
<CustomField>
    <fullName>Thematic__c</fullName>
    <label>Thematic</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Democracy</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/multiLwcCtrl.cls
public with sharing class multiLwcCtrl {
            @AuraEnabled(cacheable=true)
            public static List<Opportunity> getOpportunityList(String recordId){
                List<Opportunity> oppList = New List<Opportunity>();
                oppList = [SELECT Id,Thematic__c,Total__c,Democracy__c,Disaster__c,Education__c,Environment__c,Labor__c FROM Opportunity where id =: recordId];
                return oppList;
            }
        }